### ISSUE TITLE
[BUG] 4C not compiling on LNM clusters

### ISSUE THREAD

**Issue by davidrudlstorfer** [4C-multiphysics/4C#1304]
## Bug Description: What's going wrong?

Since yesterday 4C no longer compiles on our clusters

see

https://gitlab.lrz.de/baci/baci-config-lnm/-/jobs/11759757

and 

https://gitlab.lrz.de/baci/baci-config-lnm/-/jobs/11759760.

The problem appears to be:

```
/home/gitlab-runner/builds/LfDka8JgZ/0/baci/baci-config-lnm/src/core/linalg/src/dense/4C_linalg_serialdensevector.hpp:16:10: fatal error: c++/13/span: No such file or directory
   16 | #include <c++/13/span>
      |          ^~~~~~~~~~~~~
compilation terminated.
```

which was introduced in #1297 .

@sebproell you probably know how to solve this faster than me 

## Your Environment

- **Relevant repo SHA1s:**
- **Relevant configure flags or configure script:**
- **Operating system and version:**
- **Compiler and TPL versions:**

## Related Issues and Pull Requests

- Blocks
- Follows
- Related to
- Part of
- Composed of
