### PR TITLE
Fix: include of span in serial dense vector

### LINKED ISSUE #1304: [BUG] 4C not compiling on LNM clusters
## Bug Description: What's going wrong?

Since yesterday 4C no longer compiles on our clusters

see

https://gitlab.lrz.de/baci/baci-config-lnm/-/jobs/11759757

and 

https://gitlab.lrz.de/baci/baci-config-lnm/-/jobs/11759760.

The problem appears to be:

```
/home/gitlab-runner/builds/LfDka8JgZ/0/baci/baci-config-lnm/src/core/linalg/src/dense/4C_linalg_serialdensevector.hpp:16:10: fatal error: c++/13/span: No such file or directory
   16 | #include <c++/13/span>
      |          ^~~~~~~~~~~~~
compilation terminated.
```

which was introduced in #1297 .

@sebproell you probably know how to solve this faster than me 

## Your Environment

- **Relevant repo SHA1s:**
- **Relevant configure flags or configure script:**
- **Operating system and version:**
- **Compiler and TPL versions:**

## Related Issues and Pull Requests

- Blocks
- Follows
- Related to
- Part of
- Composed of

### PR DESCRIPTION
**Pull request by davidrudlstorfer**
## Description and Context

Does this already solve the problem of #1304 ?

## Related Issues and Pull Requests

Closes #1304

### CODE REVIEW

**Review by amgebauer — APPROVED** [review]

**Comment by sebproell** [comment]
Thanks!

**Comment by davidrudlstorfer** [comment]
@sebproell should/could we catch these includes with our include checker during the pre-commit hook? I guess there's not a real pattern we could check for?

**Comment by sebproell** [comment]
> @sebproell should/could we catch these includes with our include checker during the pre-commit hook? I guess there's not a real pattern we could check for?

I had the same idea and am already expanding the check.

**Comment by davidrudlstorfer** [comment]
> I had the same idea and am already expanding the check.

Nice! Do you want to push to this PR, otherwise I set to auto-merge

**Comment by sebproell** [comment]
This is a separate topic for another PR.
